objects/Audit_Finding__c.object
<CustomObject>
    <fields>
        <fullName>Audit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Audit</label>
        <referenceTo>CMPL123QMS__Internal_Audit__c</referenceTo>
        <relationshipLabel>Audit Findings</relationshipLabel>
        <relationshipName>Audit_Findings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Audit Finding</label>
    <nameField>
        <displayFormat>AF-{00000}</displayFormat>
        <label>Audit Finding Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Audit Findings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AuditFindingHandler.cls
/*
File Name: AuditFindingHandler
Author: Sparta Systems
Description: public class which is used to handle all the custom functioanlity on audit finding object. 
*/
public with sharing class AuditFindingHandler{

    /*
    Input: List< Audit_Finding__c >
    Output: Void
    Description: public method, which is referenced in the audit finding audit trigger, 
                 used to prevent deletion on closed complaints.
    Requirement: JIRA 303-A, Audit findings cannot be added or removed or edited after audit has been approved
    */
    public static void preventAuditFindingDelete(List< Audit_Finding__c > existingAuditFindings){
        Set<String> auditIds = new Set<String>();
        
        for(Audit_Finding__c t : existingAuditFindings)
               if(t.Audit__c != null)      
                   auditIds.add(t.Audit__c);
        
        Set<Id> AuditApprovedIdsSet = new Set<Id>();
        
        for(CMPL123QMS__Internal_Audit__c cp : [Select Id From CMPL123QMS__Internal_Audit__c Where Id IN :auditIds and Initial_Approval_Complete__c=true limit 49999])
            AuditApprovedIdsSet.add(cp.Id);
        
        for(Audit_Finding__c t : existingAuditFindings) 
            if(t.Audit__c != null && AuditApprovedIdsSet.contains(t.Audit__c))
                t.addError('Audit findings cannot be removed after audit has been approved');    
        
    }
    
}