objects/Field_Observation__c.object
<CustomObject>
    <fields>
        <fullName>Description_of_Observation__c</fullName>
        <description>A simple text field to allow agents to create simple observations</description>
        <label>Description of Observation</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reporter_Email__c</fullName>
        <label>Reporter Email</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <description>A custom Object for field agents to initiate deviations and complaints.</description>
    <label>Field Observation</label>
    <nameField>
        <label>Field Observation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Field Observations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/FieldObservationHandler.cls
global class FieldObservationHandler implements Messaging.InboundEmailHandler {
    global Messaging.InboundEmailResult handleInboundEmail(Messaging.InboundEmail email, Messaging.InboundEnvelope envelope) {
        Messaging.InboundEmailResult result = new Messaging.InboundEmailResult();
        String body = email.plainTextbody;
        body = body.abbreviate(255);
        String title = email.subject;
        String fromVal = email.fromAddress;
        Field_Observation__c observation = new Field_Observation__c(description_of_observation__c = body,name= title,reporter_email__c = fromVal);
        insert observation;
   
        List<Messaging.InboundEmail.BinaryAttachment> attachments  = email.binaryAttachments;
        
      
        if(attachments == null) {//No Attachments, move along
            return result;
        }
        for(Messaging.InboundEmail.BinaryAttachment attachment :attachments) {
                Attachment observationAttachments = new Attachment(body = attachment.body, name = attachment.fileName, parentId = observation.Id);
            	
                insert observationAttachments;
        }
    

        
        update observation;
        return result;
    }
}